name: CI
on:
  push:
#    branches:
#      - main
#    paths:
#      - installations

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: print ref
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
