name: CI
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      git_version_major: ${{ steps.set-out.outputs.oui }}
    steps:
      - uses: actions/checkout@v3
      - name: set out
        id: set-out
        run: echo "::set-output name=oui::lavaleur"

  other:
    uses: ./.github/workflows/reusable.yml
    name: Reuse
    needs: [ build ] 
