name: CI
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/
        with:
          project-name: ${{ env.RPM_VERSION_MAJOR }}/${{ env.RPM_VERSION_MINOR }}/Installers/linux/
          version: Release9382
          rpm-artifact-name: cfmapperCIBC-${{ env.RPM_VERSION_MAJOR }}.${{ env.RPM_VERSION_MINOR }}-9382.x86_64.rpm
          devarch-user: livraison
          create_rpm: false
